return {
	mod_description = {
		en = "Display unlock details for cosmetics",
		--de= "",
		--fr="",
		--it="",
		ko = "화장품 잠금 해제 세부정보 표시"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""

	},
	ordo_docket_amount_text = {
		en = " for " .. "!content" .. " Ordo Dockets",
		--de= "",
		--fr="",
		--it="",
		ko = "에서 " .. "!content" .. " 오도 명세서로 구매할 수 있습니다"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	penance_amount_singular_text = {
		en = "Requires the following penance to complete",
		--de= "",
		--fr="",
		--it="",
		ko = "획득하려면 아래의 고행을 완료해야 합니다"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	penance_amount_multiple_text = {
		en = "Requires the following " .. "!content" .. " penances to complete",
		--de= "",
		--fr="",
		--it="",
		ko = "획득하려면 아래 " .. "!content" .. " 개의 고행을 완료해야 합니다"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	hestias_blessings_obtained_text = {
		en = "Hestia's Blessings at " .. "!content" .. " penance points",
		--de= "",
		--fr="",
		--it="",
		ko = "헤스티아의 축복에서 " .. "!content" .. "  점의 고행 점수가 필요합니다"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	hestias_blessings_current_text = {
		en = "You currently have " .. "!content" .. " penance points",
		--de= "",
		--fr="",
		--it="",
		ko = "당신의 현재 고행 점수는 " .. "!content" .. " 점입니다"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	imperial_edition = {
		en = "Darktide: Imperial Edition",
		--de= "",
		--fr="",
		--it="",
		ko = "다크타이드: 임페리얼 에디션"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	twitch_drop = {
		en = "Darktide Twitch Drop",
		--de= "",
		--fr="",
		--it="",
		ko = "다크타이드 트위치 드롭스"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	first_year = {
		en = "Playing Darktide on PC before November 17, 2023",
		--de= "",
		--fr="",
		--it="",
		ko = "2023년 11월 17일 이전 PC에서 다크타이드 플레이"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	beta = {
		en = "Participating in the Darktide Beta",
		--de= "",
		--fr="",
		--it="",
		ko = "다크타이드 베타에 참여하기"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	default_item = {
		en = "Default Item",
		--de= "",
		--fr="",
		--it="",
		ko = "기본 아이템"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	pre_order = {
		en = "Pre-Order Item",
		--de= "",
		--fr="",
		--it="",
		ko = "사전예약 아이템"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	},
	redacted = {
		en = "++ REDACTED ++",
		--de= "",
		--fr="",
		--it="",
		ko = "++ 편집됨 ++"
		--es = "",
		--["zh-cn"] = "",
		--["zh-tw"] = "",
		--ru = "",
		--jp = "",
		--pl = "",
		--["pt-br"] = ""
	}
}
